[general]
# Original: LINES_COUNT_TO_READ = 1_000_000_000
LINES_COUNT_TO_READ = 1_000_000
APPROXIMATE_TRAIN_RATIO = 0.8
LOG_FILE = "./artifacts/logs/app.log"

[als]
# Original: HYPER_N_EPOCH = 30
HYPER_N_EPOCH = 20

# Original: HYPER_N_FACTOR = 10
HYPER_N_FACTOR = 10

HYPER_GAMMA = 0.1
HYPER_LAMBDA = 0.1
HYPER_TAU = 0.1
CHECKPOINT_FOLDER = "./artifacts/checkpoints/als"

[figures]
PLT_FIGURE_FOLDER = "./artifacts/figures"
PLT_FIGURE_FORMAT = "pdf"
